### ISSUE TITLE
возвращать имеет смысл ссылку на текущий экземпляр

### ISSUE THREAD

**Issue by temikdark** [Burgos1337/object-oriented-programming#2]
https://github.com/Burgos1337/objective-oriented-programming/blob/c5f7b769473ff5a09eaf0c5e3efc3ebcd6a3e22d/Prog2/Cassini.h#L15

**Comment by Burgos1337** [comment]
https://github.com/Burgos1337/object-oriented-programming/blob/4a7d68ec7120e89960e2f6766a5ecfc0796e9ce0/Prog2/Cassini.h#L14
