### ISSUE TITLE
Имеет смысл перенести обработку исключений из прикладной программы в функцию перегрузки оператора

### ISSUE THREAD

**Issue by Anastasia-kolp** [Burgos1337/object-oriented-programming#4]
https://github.com/Burgos1337/object-oriented-programming/blob/5429e347f7db1049ff934139a56ce674ee26142d/Prog3/Prog3A/train.cpp#L83

https://github.com/Burgos1337/object-oriented-programming/blob/5429e347f7db1049ff934139a56ce674ee26142d/Prog3/Prog3A/dialog.cpp#L73

**Comment by Burgos1337** [comment]
https://github.com/Burgos1337/object-oriented-programming/blob/2fb0bc2756bdba291bb8faf7ac957e9087c059fe/Prog3/Prog3A/train.cpp#L101

https://github.com/Burgos1337/object-oriented-programming/blob/2fb0bc2756bdba291bb8faf7ac957e9087c059fe/Prog3/Prog3A/dialog.cpp#L73
