### ISSUE TITLE
Оператор, не прошедший тестирование, используется в тестировании другой функции

### ISSUE THREAD

**Issue by Anastasia-kolp** [Burgos1337/object-oriented-programming#5]
https://github.com/Burgos1337/object-oriented-programming/blob/4a7d68ec7120e89960e2f6766a5ecfc0796e9ce0/Prog3/Prog3B/test.cpp#L101

https://github.com/Burgos1337/object-oriented-programming/blob/4a7d68ec7120e89960e2f6766a5ecfc0796e9ce0/Prog3/Prog3B/test.cpp#L141

**Comment by Burgos1337** [comment]
https://github.com/Burgos1337/object-oriented-programming/blob/2fb0bc2756bdba291bb8faf7ac957e9087c059fe/Prog3/Prog3B/test.cpp#L101
