### ISSUE TITLE
Может стоит передавать в качестве параметра экземпляр класса carriage?

### ISSUE THREAD

**Issue by Anastasia-kolp** [Burgos1337/object-oriented-programming#6]
https://github.com/Burgos1337/object-oriented-programming/blob/3577b553c6ba6e823ef9eb92e06239a7721330f7/Prog3/Prog3B/train.h#L17

https://github.com/Burgos1337/object-oriented-programming/blob/3577b553c6ba6e823ef9eb92e06239a7721330f7/Prog3/Prog3B/train.h#L34

**Comment by Burgos1337** [comment]
https://github.com/Burgos1337/object-oriented-programming/blob/2fb0bc2756bdba291bb8faf7ac957e9087c059fe/Prog3/Prog3B/train.h#L17

https://github.com/Burgos1337/object-oriented-programming/blob/2fb0bc2756bdba291bb8faf7ac957e9087c059fe/Prog3/Prog3B/train.h#L34
